import Foundation

enum DefaultContentConfig {
    static let sources: [FeedSource] = [
        FeedSource(id: "openai", name: "OpenAI", url: "https://openai.com/blog/rss.xml", reputation: 1.25),
        FeedSource(id: "google-ai", name: "Google AI Blog", url: "https://blog.google/technology/ai/rss/", reputation: 1.2),
        FeedSource(id: "deepmind", name: "DeepMind", url: "https://deepmind.google/blog/rss.xml", reputation: 1.25),
        FeedSource(id: "microsoft-research", name: "Microsoft Research", url: "https://www.microsoft.com/en-us/research/feed/", reputation: 1.15),
        FeedSource(id: "mit-ai", name: "MIT News - AI", url: "https://news.mit.edu/rss/topic/artificial-intelligence2", reputation: 1.15),
        FeedSource(id: "hugging-face", name: "Hugging Face Blog", url: "https://huggingface.co/blog/feed.xml", reputation: 1.2),
        FeedSource(id: "pytorch", name: "PyTorch Blog", url: "https://pytorch.org/blog/feed.xml", reputation: 1.2),
        FeedSource(id: "arxiv-robotics", name: "ArXiv Robotics", url: "https://export.arxiv.org/rss/cs.RO", reputation: 1.05),
        FeedSource(id: "arxiv-cv", name: "ArXiv Computer Vision", url: "https://export.arxiv.org/rss/cs.CV", reputation: 1.05),
        FeedSource(id: "ieee-spectrum", name: "IEEE Spectrum", url: "https://spectrum.ieee.org/feeds/feed.rss", reputation: 1.1),
        FeedSource(id: "techxplore-robotics", name: "TechXplore Robotics", url: "https://techxplore.com/rss-feed/robotics-news/", reputation: 1.0),
        FeedSource(id: "techxplore-cs", name: "TechXplore Computer Science", url: "https://techxplore.com/rss-feed/computer-sciences-news/", reputation: 1.0),
        FeedSource(id: "bair", name: "BAIR Blog", url: "https://bair.berkeley.edu/blog/feed.xml", reputation: 1.1),
        FeedSource(id: "karpathy", name: "Andrej Karpathy", url: "https://karpathy.bearblog.dev/feed/", reputation: 1.15, kind: .person),
        FeedSource(id: "mit-robotics", name: "MIT CSAIL Robotics", url: "https://news.mit.edu/topic/mitrobotics-rss.xml", reputation: 1.1),
        FeedSource(id: "robot-brains", name: "Robot Brains Podcast", url: "https://feeds.acast.com/public/shows/the-robot-brains", reputation: 1.0, kind: .person),
        FeedSource(id: "marginal-revolution", name: "Marginal Revolution", url: "https://feeds.feedblitz.com/marginalrevolution", reputation: 1.05, kind: .person),
        FeedSource(id: "paul-krugman", name: "Paul Krugman", url: "https://paulkrugman.substack.com/feed", reputation: 1.0, kind: .person),
        FeedSource(id: "noahpinion", name: "Noahpinion", url: "https://www.noahpinion.blog/feed", reputation: 1.05, kind: .person),
        FeedSource(id: "abnormal-returns", name: "Abnormal Returns", url: "https://abnormalreturns.com/feed", reputation: 1.1, kind: .person),
        FeedSource(id: "reformed-broker", name: "The Reformed Broker", url: "https://thereformedbroker.com/feed", reputation: 1.05, kind: .person),
        FeedSource(id: "innermost-loop", name: "Alex Wissner-Gross", url: "https://theinnermostloop.substack.com/feed", reputation: 1.0, kind: .person)
    ]

    static let keywords: [String: Double] = [
        "computer vision": 3.0,
        "pytorch": 2.5,
        "sensor": 2.0,
        "sensors": 2.0,
        "tactile": 3.0,
        "haptic": 2.5,
        "haptics": 2.5,
        "touch sensing": 2.5,
        "force sensing": 2.0,
        "grasp": 2.0,
        "grasping": 2.0,
        "manipulation": 2.5,
        "dexterous": 2.5,
        "machine learning": 1.5,
        "deep learning": 1.5,
        "neural network": 1.5,
        "CNN": 2.0,
        "convolutional": 2.0,
        "image recognition": 2.5,
        "object detection": 2.5,
        "semantic segmentation": 2.5,
        "depth estimation": 2.5,
        "3D": 2.0,
        "autonomous": 1.5,
        "robotics": 2.5,
        "robot": 2.0,
        "edge": 2.0,
        "embedded": 2.0,
        "optimization": 1.5,
        "inference": 1.5,
        "model compression": 2.0,
        "quantization": 2.0,
        "economics": 2.0,
        "economy": 2.0,
        "inflation": 2.0,
        "monetary policy": 2.5,
        "fiscal policy": 2.5,
        "GDP": 2.0,
        "recession": 2.0,
        "market": 1.5,
        "stock": 1.5,
        "investing": 2.0,
        "portfolio": 2.0,
        "trading": 1.8,
        "equity": 2.0,
        "bonds": 2.0,
        "ETF": 2.0,
        "valuation": 2.0,
        "dividend": 2.0,
        "bull market": 2.5,
        "bear market": 2.5,
        "AI agents": 3.0,
        "startup": 2.0,
        "funding": 2.0,
        "enterprise adoption": 2.5,
        "SEC filing": 2.5,
        "guidance": 2.0
    ]
}
